export const GET_ERRORS = "GET_ERRORS";

// Etudiant Actions
export const GET_ETUDIANTS = "GET_ETUDIANTS";
export const GET_ETUDIANT = "GET_ETUDIANT";
export const DELETE_ETUDIANT = "DELETE_ETUDIANT";
export const GET_MATIERES_OF_ETUDIANT = "GET_MATIERES_OF_ETUDIANT";
export const DELETE_MATIERE_OF_ETUDIANT = "DELETE_MATIERE_OF_ETUDIANT";

// Professeur Actions
export const GET_PROFESSEURS = "GET_PROFESSEURS";
export const GET_PROFESSEUR = "GET_PROFESSEUR";
export const DELETE_PROFESSEUR = "DELETE_PROFESSEUR";
export const GET_MATIERES_OF_PROFESSEUR = "GET_MATIERES_OF_PROFESSEUR";
export const DELETE_MATIERE_OF_PROFESSEUR = "DELETE_MATIERE_OF_PROFESSEUR";

// Matiere Actions
export const GET_MATIERES = "GET_MATIERES";
export const GET_MATIERE = "GET_MATIERE";
export const DELETE_MATIERE = "DELETE_MATIERE";
export const GET_ETUDIANTS_OF_MATIERE = "GET_ETUDIANTS_OF_MATIERE";
export const GET_PROFESSEURS_OF_MATIERE = "GET_PROFESSEURS_OF_MATIERE";

// Security Actions
export const SET_CURRENT_USER = "SET_CURRENT_USER";